### ISSUE TITLE
The progress bar on the ranking is not working well

### ISSUE THREAD

**Issue by saleiva** [Vizzuality/NEEMO#26]

**Comment by andrewxhill** [comment]
I think what you mean is that you want to work in steps? So 50 pts between levels or something? So the progress bar would equal the remainder of score/50 ? Right now it is the same as meters and we don't want that.

**Comment by saleiva** [comment]
-If possible - I'd prefer something more exponential like... 50,100,200,500,1000,2000,... :P

**Comment by javierarce** [comment]
Yes, Andrew, I wanted to do that. I suppose we'll have to split the code, then.… but first we should decide how is this thing going to work exactly… :) Exponentially? What?

**Comment by saleiva** [comment]
Nah, just do it linear for the time being...
