### ISSUE TITLE
Preload more pictures

### ISSUE THREAD

**Issue by javierarce** [Vizzuality/NEEMO#43]
Would it be possible to preload three or four pictures instead of two as we are doing now?

**Comment by javierarce** [comment]
Ok, we better don't do this. Since now we're adding scrollbars for people with small screens, I added a fixed maximum width for the app. Preloading more pictures means that we'll have to increase the maximum width of the app, and then people with not-so-small monitors will see scrollbars too, which is ugly.

**Comment by andrewxhill** [comment]
Ok, no problem. I could just preload the images so they are in the dom. If you are seeing loading issues, I'll work on this.

**Comment by andrewxhill** [comment]
btw there was already a fixed max forward buffer as this._forwardBuffer in Slideshow. It was 3.
