### ISSUE TITLE
Now user profile sometimes obscured by main image on mission page

### ISSUE THREAD

**Issue by andrewxhill** [Vizzuality/NEEMO#9]
based on small window

**Comment by javierarce** [comment]
Ok, I've moved the slideshow to right a bit more.

**Comment by javierarce** [comment]
And I've also changed the z-index, so it won't be behind the slideshow.

**Comment by andrewxhill** [comment]
I put you back at region 0, there are some position issues that we need to sort out still.

**Comment by javierarce** [comment]
You mean there are still problems with the left column? Can you send me a screen capture?
